[build]
  command = "npm install && npm run build:ci"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  command = "npm run build"

# Optional: Plugin for form handling (if you add forms later)
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
