[build]
  # Build command
  command = "npm run build"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Enable build optimization
  NODE_ENV = "production"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache the main HTML file
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    # Don't cache service worker
    Cache-Control = "public, max-age=0, must-revalidate"

# Optional: Branch deploys
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Optional: Plugin for form handling (if you add forms later)
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
